### ISSUE TITLE
declaring an MFI as a field causes error

### ISSUE THREAD

**Issue by Starwaster** [sarbian/ModularFlightIntegrator#1]
declaring a ModularFlightIntegrator field

```
        public ModularFlightIntegrator fi;
```

produces the following error
(it was in a PartModule derived  class; I was going to try to cache the FI there for access in methods outside the delegates. Not a biggie, I'll do things differently but this seemed odd and it'd be nice to know why it happened)
log here: https://www.dropbox.com/s/2c5h53nergs11tp/output_log.MFI.txt?dl=0

```
Non platform assembly: C:\Games\KSP_win_1.0\GameData\ModuleManager.dll (this message is harmless)
Non platform assembly: C:\Games\KSP_win_1.0\GameData\DeadlyReentry\Plugins\DeadlyReentry.dll (this message is harmless)
AssemblyLoader: Exception loading 'DeadlyReentry': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)

  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 

  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'DeadlyReentry.ModuleAeroReentry' from assembly 'DeadlyReentry, Version=6.6.5599.6759, Culture=neutral, PublicKeyToken=null'.
```

**Comment by sarbian** [comment]
I guess it s a loading order problem. I added a KSPAssembly tag to the Assembly info so if you add that to yours they should load in the right order : 

[assembly: KSPAssemblyDependency("ModularFlightIntegrator", 1, 0)]
