### ISSUE TITLE
Debug console spammed by missing method get_PartThermalDataList

### ISSUE THREAD

**Issue by glubo** [sarbian/ModularFlightIntegrator#2]
I got debug log spammed by `[Exception]: MissingMethodException: Method not found: 'ModularFI.ModularFlightIntegrator.get_PartThermalDataList'.` What additional info would be helpful?

**Comment by Starwaster** [comment]
Being taken care of. The problem is that the file that CKAN is downloading is out of date. Sarbian did a pull request to CKAN to fix it. In the meantime you can download a file that works here: https://ksp.sarbian.com/jenkins/job/ModularFlightIntegrator/

**Comment by glubo** [comment]
Thanks a lot for solution!
