### ISSUE TITLE
Versioning Issues

### ISSUE THREAD

**Issue by ghost** [sarbian/ModularFlightIntegrator#3]
I just spent about two hours hunting for why I was getting endless errors like:

```
[EXC 15:38:27.750] MissingMethodException: Method not found: 'ModularFI.ModularFlightIntegrator.get_PartThermalDataList'.
    UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
    DeadlyReentry.ModuleAeroReentry:FixedUpdate()
```

when running Deadly Reentry, FAR, and their common prerequisite ModularFlightIntegrator installed via CKAN.  It turns out that the version I have installed is marked as version 1.0.0.0... yet looking at it in MonoDevelop-Unity it is clearly not the correct version, as the `PartThermalDataList` field is missing.  This lead to a huge slew of exceptions as Deadly Reentry uses that field in the `FixedUpdate` method.

While I am glad I figured it out, the main cause seems to be the lack of well documented release information on this mod and sloppy recordkeeping in the CKAN-meta repository, [having the same "version" of the mod updated to point to new files each time.](https://github.com/KSP-CKAN/CKAN-meta/commits/master/ModularFlightIntegrator/ModularFlightIntegrator-1.0.ckan)

**Comment by ghost** [comment]
Checking the hashes, I seem to have the from build 5.

**Comment by sarbian** [comment]
The 2 versions were released 6H apart before there was any mods using it published. 
The initial CKAN pull was wrong. It has nothing to do with MFI.
